#!/bin/sh

OTP_VERSION=${OTP_VERSION:-18.3}
filename="otp_src_${OTP_VERSION}"
archive="${filename}.tar.gz"
erl_url="http://www.erlang.org/download/${archive}"
prefix="/usr/local/erlang"

apt-get update
apt-get upgrade -y --show-upgraded
apt-get install -y build-essential
apt-get install -y m4 fop libncurses5-dev openssl libssl-dev tk unixodbc unixodbc-dev freeglut3-dev libwxgtk2.8-dev xsltproc

[ ! -s ${archive} ] && wget -c -O ${archive} $erl_url

tar zxvf ${archive}
cd ${filename}

./configure --prefix=$prefix --without-javac \
    --enable-kernel-poll \
    --enable-threads \
    --enable-dynamic-ssl-lib \
    --enable-shared-zlib \
    --enable-smp-support \
    --enable-hipe

make && make install

ln -sfv $prefix/bin/* /usr/local/bin/

cd .. && rm -rf ${filename}
apt-get autoclean -y
apt-get clean -y
apt-get autoremove -y

erl -noshell -eval "erlang:display('Erlang Success Install')" -s init stop